# Generated by Django 5.2.7 on 2025-10-18 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('doctor', 'doctor'), ('patient', 'patient')], default='patient', max_length=32)),
                ('age', models.CharField(blank=True, max_length=16, null=True)),
                ('gender', models.CharField(blank=True, max_length=16, null=True)),
                ('insurance', models.CharField(blank=True, max_length=128, null=True)),
                ('specialty', models.CharField(blank=True, max_length=128, null=True)),
                ('clinic', models.CharField(blank=True, max_length=128, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
